#Nginx Complete Proxy Mapping
events {}

http {

    upstream auth_service {
        server auth-service:3001;
    }

    upstream device_service {
        server device-service:3002;
    }

    upstream risk_engine {
        server risk-engine:3003;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/device/ {
            proxy_pass http://device_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/risk/ {
            proxy_pass http://risk_engine/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
